kind: pipeline
type: docker
name: react-build

trigger:
  branch:
    - deploy
  event:
    - push

steps:
  - name: install-dependencies
    image: node:18
    commands:
      - npm ci

  - name: run-tests
    image: node:18
    commands:
      - npm test

  - name: build
    image: node:18
    commands:
      - npm run build

  # - name: deploy
  #   image: appleboy/drone-scp
  #   settings:
  #     host: 172.235.18.144
  #     username: root
  #     key:
  #       from_secret: ssh_key
  #     source: build/
  #     target: /var/www/html/p1/
