kind: pipeline
type: docker
name: build-and-serve-react

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: install-essentials
    image: node:18
    commands:
      - npm install
      - npm run build

  - name: build-reddit-client
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t reddit-client:latest .

  - name: run-react-container
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop reddit-client || true
      - docker rm reddit-client || true
      - docker run -d --name reddit-client -p 6502:80 reddit-client:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
